=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Tremendous
  # Filters object for a `report_type: digital_rewards` report 
  class CreateReportRequestFiltersDigitalRewards < ApiModelBase
    attr_accessor :amount

    # ID of the Tremendous campaign that this report should be limited to 
    attr_accessor :campaign_id

    attr_accessor :created_at

    # Delivery date for gifts that should be returned in the report 
    attr_accessor :delivered_at

    # Delivery method for rewards returned in the report 
    attr_accessor :delivery_method

    # ID of the Tremendous order that this report should be limited to 
    attr_accessor :order_id

    # Order status for rewards returned in the report 
    attr_accessor :order_status

    # Status for rewards returned in the report 
    attr_accessor :status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'campaign_id' => :'campaign_id',
        :'created_at' => :'created_at',
        :'delivered_at' => :'delivered_at',
        :'delivery_method' => :'delivery_method',
        :'order_id' => :'order_id',
        :'order_status' => :'order_status',
        :'status' => :'status'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'CreateReportRequestFiltersDigitalRewardsAmount',
        :'campaign_id' => :'String',
        :'created_at' => :'CreateReportRequestFiltersDigitalRewardsCreatedAt',
        :'delivered_at' => :'Date',
        :'delivery_method' => :'String',
        :'order_id' => :'String',
        :'order_status' => :'String',
        :'status' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'amount',
        :'campaign_id',
        :'created_at',
        :'delivered_at',
        :'delivery_method',
        :'order_id',
        :'order_status',
        :'status'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Tremendous::CreateReportRequestFiltersDigitalRewards` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Tremendous::CreateReportRequestFiltersDigitalRewards`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'delivered_at')
        self.delivered_at = attributes[:'delivered_at']
      end

      if attributes.key?(:'delivery_method')
        self.delivery_method = attributes[:'delivery_method']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'order_status')
        self.order_status = attributes[:'order_status']
      end

      if attributes.key?(:'status')
        if (value = attributes[:'status']).is_a?(Array)
          self.status = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      delivery_method_validator = EnumAttributeValidator.new('String', ["phone", "email", "link", "mail", "direct"])
      return false unless delivery_method_validator.valid?(@delivery_method)
      order_status_validator = EnumAttributeValidator.new('String', ["executed", "canceled", "failed", "pending_approval"])
      return false unless order_status_validator.valid?(@order_status)
      true
    end

    # Custom attribute writer method for enum attributes. Any value is accepted
    # so that enum values added to the API don't break deserialization on
    # older versions of this gem.
    # @param [Object] delivery_method Object to be assigned
    def delivery_method=(delivery_method)
      @delivery_method = delivery_method
    end

    # Custom attribute writer method for enum attributes. Any value is accepted
    # so that enum values added to the API don't break deserialization on
    # older versions of this gem.
    # @param [Object] order_status Object to be assigned
    def order_status=(order_status)
      @order_status = order_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          campaign_id == o.campaign_id &&
          created_at == o.created_at &&
          delivered_at == o.delivered_at &&
          delivery_method == o.delivery_method &&
          order_id == o.order_id &&
          order_status == o.order_status &&
          status == o.status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, campaign_id, created_at, delivered_at, delivery_method, order_id, order_status, status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
