=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Tremendous
  # A list of the settings that you wish to copy over to the new organization.
  class CreateOrganizationRequestCopySettings < ApiModelBase
    # Copy over the campaigns from the current organization to the new organization. Defaults to `false`.
    attr_accessor :campaigns

    # Copy over the custom fields from the current organization to the new organization. Defaults to `false`.
    attr_accessor :custom_fields

    # Copy over the order approvals settings from the current organization to the new organization. Defaults to `false`.
    attr_accessor :order_approvals

    # Copy over the payment methods from the current organization to the new organization. Defaults to `false`.
    attr_accessor :payment_methods

    # Copy over the security settings from the current organization to the new organization. Defaults to `true`.
    attr_accessor :security_settings

    # Copy over the users and custom roles from the current organization to the new organization. Defaults to `false`.
    attr_accessor :users

    # Copy over the custom roles from the current organization to the new organization. Custom roles are always copied if `users` is `true`. Defaults to `false`.
    attr_accessor :custom_roles

    # Copy over the fraud prevention settings and rules from the current organization to the new organization. Defaults to `false`.
    attr_accessor :fraud_prevention

    # Copy over the tax management settings, including the association with the parent tax entity, from the current organization to the new organization. Defaults to `false`.
    attr_accessor :tax_management

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'campaigns' => :'campaigns',
        :'custom_fields' => :'custom_fields',
        :'order_approvals' => :'order_approvals',
        :'payment_methods' => :'payment_methods',
        :'security_settings' => :'security_settings',
        :'users' => :'users',
        :'custom_roles' => :'custom_roles',
        :'fraud_prevention' => :'fraud_prevention',
        :'tax_management' => :'tax_management'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'campaigns' => :'Boolean',
        :'custom_fields' => :'Boolean',
        :'order_approvals' => :'Boolean',
        :'payment_methods' => :'Boolean',
        :'security_settings' => :'Boolean',
        :'users' => :'Boolean',
        :'custom_roles' => :'Boolean',
        :'fraud_prevention' => :'Boolean',
        :'tax_management' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Tremendous::CreateOrganizationRequestCopySettings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Tremendous::CreateOrganizationRequestCopySettings`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'campaigns')
        self.campaigns = attributes[:'campaigns']
      else
        self.campaigns = false
      end

      if attributes.key?(:'custom_fields')
        self.custom_fields = attributes[:'custom_fields']
      else
        self.custom_fields = false
      end

      if attributes.key?(:'order_approvals')
        self.order_approvals = attributes[:'order_approvals']
      else
        self.order_approvals = false
      end

      if attributes.key?(:'payment_methods')
        self.payment_methods = attributes[:'payment_methods']
      else
        self.payment_methods = false
      end

      if attributes.key?(:'security_settings')
        self.security_settings = attributes[:'security_settings']
      else
        self.security_settings = true
      end

      if attributes.key?(:'users')
        self.users = attributes[:'users']
      else
        self.users = false
      end

      if attributes.key?(:'custom_roles')
        self.custom_roles = attributes[:'custom_roles']
      else
        self.custom_roles = false
      end

      if attributes.key?(:'fraud_prevention')
        self.fraud_prevention = attributes[:'fraud_prevention']
      else
        self.fraud_prevention = false
      end

      if attributes.key?(:'tax_management')
        self.tax_management = attributes[:'tax_management']
      else
        self.tax_management = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          campaigns == o.campaigns &&
          custom_fields == o.custom_fields &&
          order_approvals == o.order_approvals &&
          payment_methods == o.payment_methods &&
          security_settings == o.security_settings &&
          users == o.users &&
          custom_roles == o.custom_roles &&
          fraud_prevention == o.fraud_prevention &&
          tax_management == o.tax_management
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [campaigns, custom_fields, order_approvals, payment_methods, security_settings, users, custom_roles, fraud_prevention, tax_management].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
