=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Tremendous
  class FraudReviewRedemptionMethod
    BANK_TRANSFER = "bank transfer".freeze
    CASH_APP = "cash app".freeze
    CHARITY = "charity".freeze
    CRYPTO = "crypto".freeze
    INSTANT_DEBIT_TRANSFER = "instant debit transfer".freeze
    INTERNATIONAL_BANK_TRANSFER = "international bank transfer".freeze
    MERCHANT_CARD = "merchant card".freeze
    PAYPAL = "paypal".freeze
    RECIPIENT_PROMOTION = "recipient_promotion".freeze
    VENMO = "venmo".freeze
    VISA_CARD = "visa card".freeze
    ZELLE = "zelle".freeze

    def self.all_vars
      @all_vars ||= [BANK_TRANSFER, CASH_APP, CHARITY, CRYPTO, INSTANT_DEBIT_TRANSFER, INTERNATIONAL_BANK_TRANSFER, MERCHANT_CARD, PAYPAL, RECIPIENT_PROMOTION, VENMO, VISA_CARD, ZELLE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FraudReviewRedemptionMethod.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FraudReviewRedemptionMethod"
    end
  end
end
