=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module Tremendous
  class FraudRuleType
    REVIEW_COUNTRY = "review_country".freeze
    REVIEW_IP = "review_ip".freeze
    REVIEW_EMAIL = "review_email".freeze
    REVIEW_REDEEMED_REWARDS_COUNT = "review_redeemed_rewards_count".freeze
    REVIEW_REDEEMED_REWARDS_AMOUNT = "review_redeemed_rewards_amount".freeze
    REVIEW_MULTIPLE_EMAILS = "review_multiple_emails".freeze
    REVIEW_VPN = "review_vpn".freeze
    REVIEW_TREMENDOUS_FLAG_LIST = "review_tremendous_flag_list".freeze
    REVIEW_PREVIOUSLY_BLOCKED_RECIPIENTS = "review_previously_blocked_recipients".freeze
    ALLOW_IP = "allow_ip".freeze
    ALLOW_EMAIL = "allow_email".freeze

    def self.all_vars
      @all_vars ||= [REVIEW_COUNTRY, REVIEW_IP, REVIEW_EMAIL, REVIEW_REDEEMED_REWARDS_COUNT, REVIEW_REDEEMED_REWARDS_AMOUNT, REVIEW_MULTIPLE_EMAILS, REVIEW_VPN, REVIEW_TREMENDOUS_FLAG_LIST, REVIEW_PREVIOUSLY_BLOCKED_RECIPIENTS, ALLOW_IP, ALLOW_EMAIL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FraudRuleType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FraudRuleType"
    end
  end
end
