=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and its members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module Tremendous
  class ListTopups200ResponseTopupsInner
    # Unique identifier for the topup request.
    attr_accessor :id

    # Amount to add to your organization's balance, denominated in `currency_code`.
    attr_accessor :amount

    # Currency of the topup amount. Always matches the organization's currency.
    attr_accessor :currency_code

    # Amount of the processing fee for the topup (typically reserved for credit card topups).
    attr_accessor :processing_fee

    # ID of the funding_source object used for this topup.
    attr_accessor :funding_source_id

    # Status of the topup <table>   <thead>     <tr>       <th>         Status       </th>       <th>         Description       </th>     </tr>   </thead>   <tbody>     <tr>       <td>         <code>           created         </code>       </td>       <td>         The topup is processing (and may be under review).       </td>     </tr>     <tr>       <td>         <code>           partially_credited         </code>       </td>       <td>         Some funds have been credited to the balance. The remainder will be credited by <code>expected_settlement_at</code>.       </td>     </tr>     <tr>       <td>         <code>           fully_credited         </code>       </td>       <td>         All funds have been added to the balance.       </td>     </tr>     <tr>       <td>         <code>           reversed         </code>       </td>       <td>         The topup was credited, but then reversed due to a chargeback or ACH return.       </td>     </tr>     <tr>       <td>         <code>           rejected         </code>       </td>       <td>         The topup was rejected by an admin.       </td>     </tr>   </tbody> </table> 
    attr_accessor :status

    # Timestamp indicating when the topup object was created (when the request was made).
    attr_accessor :created_at

    # Timestamp indicating when the topup amount was fully credited to the balance.
    attr_accessor :fully_credited_at

    # Timestamp indicating when the topup was rejected.
    attr_accessor :rejected_at

    # Timestamp indicating when the topup was reversed.
    attr_accessor :reversed_at

    # A sentence explaining why the topup was reversed.
    attr_accessor :reversed_reason

    # Idempotency key to prevent duplicate requests.
    attr_accessor :idempotency_key

    # Amount credited to the balance immediately. Equals `amount` for non-ACH topups or ACH debits fully within instant funding limits. Can be 0 if nothing was credited instantly.
    attr_accessor :instant_credit_amount

    # Amount that will be available once the settlement period elapses. 0 if nothing is settling.
    attr_accessor :settled_amount

    # Timestamp indicating when the pending amount will be credited to the balance. Null if the topup was fully credited immediately.
    attr_accessor :expected_settlement_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'amount' => :'amount',
        :'currency_code' => :'currency_code',
        :'processing_fee' => :'processing_fee',
        :'funding_source_id' => :'funding_source_id',
        :'status' => :'status',
        :'created_at' => :'created_at',
        :'fully_credited_at' => :'fully_credited_at',
        :'rejected_at' => :'rejected_at',
        :'reversed_at' => :'reversed_at',
        :'reversed_reason' => :'reversed_reason',
        :'idempotency_key' => :'idempotency_key',
        :'instant_credit_amount' => :'instant_credit_amount',
        :'settled_amount' => :'settled_amount',
        :'expected_settlement_at' => :'expected_settlement_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'amount' => :'Float',
        :'currency_code' => :'String',
        :'processing_fee' => :'Float',
        :'funding_source_id' => :'String',
        :'status' => :'String',
        :'created_at' => :'Time',
        :'fully_credited_at' => :'Time',
        :'rejected_at' => :'Time',
        :'reversed_at' => :'Time',
        :'reversed_reason' => :'String',
        :'idempotency_key' => :'String',
        :'instant_credit_amount' => :'Float',
        :'settled_amount' => :'Float',
        :'expected_settlement_at' => :'Date'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'fully_credited_at',
        :'rejected_at',
        :'reversed_at',
        :'reversed_reason',
        :'idempotency_key',
        :'expected_settlement_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Tremendous::ListTopups200ResponseTopupsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Tremendous::ListTopups200ResponseTopupsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'currency_code')
        self.currency_code = attributes[:'currency_code']
      end

      if attributes.key?(:'processing_fee')
        self.processing_fee = attributes[:'processing_fee']
      end

      if attributes.key?(:'funding_source_id')
        self.funding_source_id = attributes[:'funding_source_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'fully_credited_at')
        self.fully_credited_at = attributes[:'fully_credited_at']
      end

      if attributes.key?(:'rejected_at')
        self.rejected_at = attributes[:'rejected_at']
      end

      if attributes.key?(:'reversed_at')
        self.reversed_at = attributes[:'reversed_at']
      end

      if attributes.key?(:'reversed_reason')
        self.reversed_reason = attributes[:'reversed_reason']
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      end

      if attributes.key?(:'instant_credit_amount')
        self.instant_credit_amount = attributes[:'instant_credit_amount']
      end

      if attributes.key?(:'settled_amount')
        self.settled_amount = attributes[:'settled_amount']
      end

      if attributes.key?(:'expected_settlement_at')
        self.expected_settlement_at = attributes[:'expected_settlement_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          amount == o.amount &&
          currency_code == o.currency_code &&
          processing_fee == o.processing_fee &&
          funding_source_id == o.funding_source_id &&
          status == o.status &&
          created_at == o.created_at &&
          fully_credited_at == o.fully_credited_at &&
          rejected_at == o.rejected_at &&
          reversed_at == o.reversed_at &&
          reversed_reason == o.reversed_reason &&
          idempotency_key == o.idempotency_key &&
          instant_credit_amount == o.instant_credit_amount &&
          settled_amount == o.settled_amount &&
          expected_settlement_at == o.expected_settlement_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, amount, currency_code, processing_fee, funding_source_id, status, created_at, fully_credited_at, rejected_at, reversed_at, reversed_reason, idempotency_key, instant_credit_amount, settled_amount, expected_settlement_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Tremendous.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
