=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module Tremendous
  class OrderStatus
    CANCELED = "CANCELED".freeze
    CART = "CART".freeze
    EXECUTED = "EXECUTED".freeze
    FAILED = "FAILED".freeze
    PENDING_APPROVAL = "PENDING APPROVAL".freeze
    PENDING_INTERNAL_PAYMENT_APPROVAL = "PENDING INTERNAL PAYMENT APPROVAL".freeze

    def self.all_vars
      @all_vars ||= [CANCELED, CART, EXECUTED, FAILED, PENDING_APPROVAL, PENDING_INTERNAL_PAYMENT_APPROVAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if OrderStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #OrderStatus"
    end
  end
end
