=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Tremendous::BalanceTransactionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BalanceTransactionsApi' do
  before do
    # run before each test
    @api_instance = Tremendous::BalanceTransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BalanceTransactionsApi' do
    it 'should create an instance of BalanceTransactionsApi' do
      expect(@api_instance).to be_instance_of(Tremendous::BalanceTransactionsApi)
    end
  end

  # unit tests for list_balance_transactions
  # List balance transactions
  # Fetch a list of all balance transactions on your account. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset Offsets the returned list by the given number of transactions. The returned transactions are ordered (and offsetted) by their creation date (DESC).
  # @option opts [Integer] :limit Limits the number of transactions listed. The default value is 10.
  # @option opts [String] :created_at_gte Only return results where the created_at field is greater than or equal to the supplied value. The string needs to be an ISO 8601 datetime.
  # @option opts [String] :created_at_lte Only return results where the created_at field is less than or equal to the supplied value. The string needs to be an ISO 8601 datetime.
  # @return [ListBalanceTransactions200Response]
  describe 'list_balance_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
