=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Tremendous::CampaignsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CampaignsApi' do
  before do
    # run before each test
    @api_instance = Tremendous::CampaignsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CampaignsApi' do
    it 'should create an instance of CampaignsApi' do
      expect(@api_instance).to be_instance_of(Tremendous::CampaignsApi)
    end
  end

  # unit tests for get_campaign
  # Retrieve campaign
  # Retrieve a campaign, identified by the given &#x60;id&#x60; in the URL 
  # @param id ID of the campaign that should be retrieved
  # @param [Hash] opts the optional parameters
  # @return [GetCampaign200Response]
  describe 'get_campaign test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_campaigns
  # List campaigns
  # Retrieve a list of all campaigns created in your account 
  # @param [Hash] opts the optional parameters
  # @return [ListCampaigns200Response]
  describe 'list_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
