=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Tremendous::FundingSourcesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FundingSourcesApi' do
  before do
    # run before each test
    @api_instance = Tremendous::FundingSourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FundingSourcesApi' do
    it 'should create an instance of FundingSourcesApi' do
      expect(@api_instance).to be_instance_of(Tremendous::FundingSourcesApi)
    end
  end

  # unit tests for get_funding_source
  # Retrieve funding source
  # Retrieve a funding source, identified by the given &#x60;id&#x60; in the URL 
  # @param id ID of the funding source that should be retrieved
  # @param [Hash] opts the optional parameters
  # @return [GetFundingSource200Response]
  describe 'get_funding_source test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_funding_sources
  # List funding sources
  # Retrieve a list of all funding sources available for ordering through the API in your organization&#39;s account. 
  # @param [Hash] opts the optional parameters
  # @return [ListFundingSources200Response]
  describe 'list_funding_sources test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
