=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Tremendous::DeliveryStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Tremendous::DeliveryStatus do
  let(:instance) { Tremendous::DeliveryStatus.new }

  describe 'test an instance of DeliveryStatus' do
    it 'should create an instance of DeliveryStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Tremendous::DeliveryStatus)
    end
  end

end
