=begin
#API Endpoints

#Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Tremendous::GetFundingSource200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Tremendous::GetFundingSource200Response do
  let(:instance) { Tremendous::GetFundingSource200Response.new }

  describe 'test an instance of GetFundingSource200Response' do
    it 'should create an instance of GetFundingSource200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Tremendous::GetFundingSource200Response)
    end
  end

  describe 'test attribute "funding_source"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
