name: Check if the Open API has changed
on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  check-update:
    if: github.repository == 'tremendous-rewards/tremendous-ruby'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: check-update
        uses: mikefarah/yq@557dcb87b8efe786f89a12c09e9046b4753ab72e
        with:
          cmd: ./bin/check-updates

      - id: create-issue
        if: ${{ steps.check-update.outputs.changed == 'true' }}
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
        with:
          update_existing: false
          filename: .github/needs-update-template.md
