name: Check if the Open API has changed
on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  check-update:
    if: github.repository == 'tremendous-rewards/tremendous-ruby'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: install-yq
        run: wget https://github.com/mikefarah/yq/releases/v4.44.1/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      - id: check-update
        run: ./bin/check-updates

      - id: create-issue
        if: ${{ steps.check-update.outputs.changed == 'true' }}
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5
        with:
          update_existing: false
          filename: .github/needs-update-template.md
