name: Run tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags-ignore:
      - 'v*'
  pull_request_target:
    branches:
      - 'main'

jobs:
  test:
    if: github.repository == 'tremendous-rewards/tremendous-ruby'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@v4
      - name: Use Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bin/rspec
        env:
          SANDBOX_API_TOKEN:  ${{ secrets.SANDBOX_API_TOKEN }}
          TEST_CAMPAIGN_ID:  ${{ secrets.TEST_CAMPAIGN_ID }}
          TEST_PRODUCT_ID:  ${{ secrets.TEST_PRODUCT_ID }}
          TEST_RECIPIENT_EMAIL:  ${{ secrets.TEST_RECIPIENT_EMAIL }}
