name: Run tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '5 12,15,18 * * 1-5'


jobs:
  test:
    if: github.repository == 'tremendous-rewards/tremendous-ruby'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']

    env:
      SANDBOX_API_TOKEN: ${{ secrets.SANDBOX_API_TOKEN }}
      TEST_CAMPAIGN_ID: ${{ secrets.TEST_CAMPAIGN_ID }}
      TEST_PRODUCT_ID: ${{ secrets.TEST_PRODUCT_ID }}
      TEST_RECIPIENT_EMAIL: ${{ secrets.TEST_RECIPIENT_EMAIL }}

    steps:
      - uses: actions/checkout@v5
      - name: Debug runner and environment info
        run: |
          echo "Runner version info:"
          if [ -f "/opt/hostedtoolcache/actions-runner/_layout" ]; then
            cat /opt/hostedtoolcache/actions-runner/_layout 2>/dev/null || echo "Layout file not accessible"
          fi
          echo "Runner OS: $(uname -a)"
          echo "Runner environment: $RUNNER_OS"
          echo "GitHub Actions Runner: $GITHUB_ACTIONS"
      - name: Debug environment variables
        run: |
          echo "SANDBOX_API_TOKEN is set: $([[ -n "$SANDBOX_API_TOKEN" ]] && echo "yes" || echo "no")"
          echo "TEST_PRODUCT_ID is set: $([[ -n "$TEST_PRODUCT_ID" ]] && echo "yes" || echo "no")"
          echo "TEST_CAMPAIGN_ID is set: $([[ -n "$TEST_CAMPAIGN_ID" ]] && echo "yes" || echo "no")"
          echo "TEST_RECIPIENT_EMAIL is set: $([[ -n "$TEST_RECIPIENT_EMAIL" ]] && echo "yes" || echo "no")"
      - name: Use Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bin/rspec

  notify:
    needs: test
    if: ${{ failure() && github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: notify
        uses: slackapi/slack-github-action@v2.1.1
        with:
          errors: true
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: "⛔ *<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}> scheduled build failed*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|build here>."
